name: Test Action
run-name: Test
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
    branches:
      - main

jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g bun
      - run: bun install
      - run: bun run build
      - run: bun run test
